# -*- coding: utf-8 -*-
"""PyTU_Github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1MOHqVTXfCYykFRm8v3chVSGO2Z14Ja
"""

## Part 1: TUS Modeling

# This script simulates a focused ultrasound beam with tissue attenuation and a 1D thermal model
# along the depth using piecewise tissue properties.
# Tissue layers based on ultrasound image:
# 0-1 cm: Skin/Fat (using Fat properties)
# 1-2 cm: Muscle
# 2-3 cm: Visceral Fat
# 3-4 cm: Mixed tissue
# 4-6.5 cm: Pancreas (target region)

import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import pandas as pd

# Acoustic simulation parameters
frequency = 1e6  # 1 MHz
sound_speed_default = 1500  # m/s
wavelength = sound_speed_default / frequency  # in m

# Define spatial grid in depth (z in cm) for simulation from 0 to 10 cm
z_min = 0
z_max = 10
dz = 0.01  # 0.01 cm resolution
z = np.arange(z_min, z_max + dz, dz)  # in cm

# Define base peak intensity in W/cm^2 (assumed at transducer surface, before attenuation)
I0 = 5  # W/cm^2 peak intensity

# Enhanced tissue properties with detailed thermal conductivity and improved skin modeling
# Values derived from Saab et al. (J Ultrasound Med 2023) and literature values
tissue_layers = [
    {
        'name': 'Epidermis',
        'start': 0,
        'end': 0.1,
        'attenuation': 4.2,  # Higher attenuation for epidermis
        'density': 1120,
        'sound_speed': 1624,
        'thermal_conductivity': 0.235,  # W/(m·K)
        'specific_heat': 3600  # J/(kg·K)
    },
    {
        'name': 'Dermis',
        'start': 0.1,
        'end': 0.4,
        'attenuation': 3.5,  # From Saab's paper, Table 1
        'density': 1109,
        'sound_speed': 1624,
        'thermal_conductivity': 0.445,  # W/(m·K)
        'specific_heat': 3300  # J/(kg·K)
    },
    {
        'name': 'Hypodermis',
        'start': 0.4,
        'end': 1.0,
        'attenuation': 2.1,  # Lower than dermis
        'density': 971,
        'sound_speed': 1450,
        'thermal_conductivity': 0.185,  # W/(m·K)
        'specific_heat': 2700  # J/(kg·K)
    },
    {
        'name': 'Muscle',
        'start': 1,
        'end': 2,
        'attenuation': 1.09,
        'density': 1050,
        'sound_speed': 1547,
        'thermal_conductivity': 0.51,  # W/(m·K)
        'specific_heat': 3421  # J/(kg·K)
    },
    {
        'name': 'Visceral Fat',
        'start': 2,
        'end': 3,
        'attenuation': 0.63,
        'density': 950,
        'sound_speed': 1478,
        'thermal_conductivity': 0.21,  # W/(m·K)
        'specific_heat': 2348  # J/(kg·K)
    },
    {
        'name': 'Mixed Tissue',
        'start': 3,
        'end': 4,
        'attenuation': 0.85,
        'density': 1000,
        'sound_speed': 1500,
        'thermal_conductivity': 0.40,  # W/(m·K)
        'specific_heat': 3500  # J/(kg·K)
    },
    {
        'name': 'Pancreas',
        'start': 4,
        'end': 6.5,
        'attenuation': 0.85,
        'density': 1045,
        'sound_speed': 1514,
        'thermal_conductivity': 0.51,  # W/(m·K), from ex vivo study
        'specific_heat': 3164  # J/(kg·K), from Saab's paper, Table 1
    }
]

# Create array for local attenuation coefficient (in dB/cm) for each depth point
att_dB = np.zeros_like(z)
k_thermal = np.zeros_like(z)  # Array for thermal conductivity
c_p = np.zeros_like(z)  # Array for specific heat capacity
density = np.zeros_like(z)  # Array for density

# Populate tissue properties arrays
for layer in tissue_layers:
    indices = np.where((z >= layer['start']) & (z < layer['end']))
    # Total attenuation at operating frequency
    att_dB[indices] = layer['attenuation'] * (frequency/1e6)
    # Thermal conductivity
    k_thermal[indices] = layer['thermal_conductivity']
    # Specific heat
    c_p[indices] = layer['specific_heat']
    # Density
    density[indices] = layer['density']

# For z >= 6.5, use pancreas properties
indices = np.where(z >= 6.5)
att_dB[indices] = 0.85 * (frequency/1e6)
k_thermal[indices] = 0.51
c_p[indices] = 3164
density[indices] = 1045

# Compute intensity profile with enhanced skin model
I = np.zeros_like(z)
I[0] = I0

cumulative_att = 0  # cumulative attenuation in dB
for i in range(1, len(z)):
    # incremental attenuation over dz at previous index
    delta_att = att_dB[i-1] * dz
    cumulative_att += delta_att
    I[i] = I0 * 10**(-cumulative_att/10)

# Plot the intensity vs. depth with clear tissue layer boundaries
plt.figure(figsize=(10,6))
plt.plot(z, I, 'b-', linewidth=2, label='Acoustic Intensity (W/cm²)')
plt.xlabel('Depth (cm)', fontsize=12)
plt.ylabel('Intensity (W/cm²)', fontsize=12)
plt.title('Acoustic Intensity vs Depth with Enhanced Skin Model', fontsize=14)
plt.grid(True)

# Add vertical lines for tissue boundaries and labels
for layer in tissue_layers:
    plt.axvline(x=layer['start'], color='gray', linestyle=':', alpha=0)
    plt.text(layer['start'] + (layer['end']-layer['start'])/2, I0*0.9,
             layer['name'], rotation=90, va='top', ha='center', fontsize=9)

plt.legend(fontsize=12)
plt.savefig('intensity_vs_depth_enhanced.png', dpi=600, bbox_inches='tight')
plt.show()

# --------------------------
# Enhanced Thermal Simulation Setup
# --------------------------
# Bioheat equation with layer-specific thermal properties
# dT/dt = (k/(rho*c)) d^2T/dz^2 + Q/(rho*c) + blood perfusion term

# Convert dz from cm to m for thermal diffusion
dz_m = dz/100

# Add blood perfusion parameters (vary by tissue)
blood_perfusion = np.zeros_like(z)  # in ml_Blood/ml_tissue/s
blood_temp = 37.0  # °C
blood_density = 1060  # kg/m³
blood_specific_heat = 3770  # J/(kg·K) from search results

# Define perfusion for each layer
perfusion_values = {
    'Epidermis': 0.0,  # No blood vessels in epidermis
    'Dermis': 0.013,
    'Hypodermis': 0.001,
    'Muscle': 0.027,
    'Visceral Fat': 0.001,
    'Mixed Tissue': 0.018,
    'Pancreas': 0.038  # From search results (slightly higher)
}

# Set perfusion values by layer
for layer in tissue_layers:
    indices = np.where((z >= layer['start']) & (z < layer['end']))
    blood_perfusion[indices] = perfusion_values[layer['name']]

# Simulation time parameters
sonication_time = 300  # seconds
dt = 0.01  # time step in seconds
nt = int(sonication_time / dt)

# Create temperature array, initial temperature 37°C everywhere
T = np.ones_like(z)*37

# Convert attenuation to Np/m for heating term
alpha_Np = att_dB * (np.log(10)/20) * 100  # Convert dB/cm to Np/m

# Calculate heating term Q (W/m³) at each depth
Q = 2 * alpha_Np * I * 10000  # Convert I from W/cm² to W/m²

# Calculate thermal diffusivity (position-dependent)
kappa = k_thermal / (density * c_p)

# Stability criterion for explicit scheme
dt_max = 0.5 * min(dz_m**2 / kappa[kappa>0])
dt = min(0.01, dt_max)  # ensure stability
nt = int(sonication_time/dt)

# Temperature evolution
T = np.ones_like(z)*37  # Initial temperature everywhere is 37°C
T_history = np.zeros((len(z), nt))  # Store temperature history
T_history[:,0] = T

# Time evolution using explicit finite difference with perfusion
print("Running enhanced thermal simulation with perfusion...")
for n in tqdm(range(1, nt)):
    # Interior points
    dT = np.zeros_like(T)
    for i in range(1, len(z)-1):
        # Diffusion term (with position-dependent thermal properties)
        diffusion = kappa[i] * (T[i+1] - 2*T[i] + T[i-1]) / dz_m**2

        # Perfusion term (Pennes model)
        perfusion = blood_perfusion[i] * blood_density * blood_specific_heat * (blood_temp - T[i]) / density[i] / c_p[i]

        # Source term
        source = Q[i] / (density[i] * c_p[i])

        # Combined temperature change
        dT[i] = dt * (diffusion + perfusion + source)

    # Boundary conditions (adiabatic)
    dT[0] = dT[1]
    dT[-1] = dT[-2]

    T = T + dT
    T_history[:,n] = T

# Plot final temperature distribution with tissue layers
plt.figure(figsize=(10,6))
plt.plot(z, T, 'r-', linewidth=2, label='Final Temperature')
plt.plot(z, T_history[:,0], 'b--', linewidth=1.5, label='Initial Temperature')

# Add vertical lines and labels for tissue layers
for layer in tissue_layers:
    plt.axvline(x=layer['start'], color='gray', linestyle=':', alpha=0)
    mid_point = layer['start'] + (layer['end']-layer['start'])/2
    plt.text(mid_point, plt.ylim()[1] - 0.2, layer['name'],
             rotation=90, va='top', ha='center', fontsize=9)

plt.xlabel('Depth (cm)', fontsize=12)
plt.ylabel('Temperature (°C)', fontsize=12)
plt.title(f'Temperature Distribution After {sonication_time}s Sonication\nWith Enhanced Skin Model & Perfusion', fontsize=14)
plt.grid(True)
plt.legend(fontsize=12)
plt.savefig('temperature_distribution_enhanced.png', dpi=600, bbox_inches='tight')
plt.show()

# Plot temperature evolution at target depth (pancreas ~5cm)
target_depth_idx = np.abs(z - 5).argmin()  # Index closest to 5cm depth
time_points = np.linspace(0, sonication_time, nt)

plt.figure(figsize=(10,6))
plt.plot(time_points, T_history[target_depth_idx,:], 'r-', linewidth=2)
plt.xlabel('Time (s)', fontsize=12)
plt.ylabel('Temperature (°C)', fontsize=12)
plt.title(f'Temperature Evolution at Target Depth (5 cm)\nWith Enhanced Skin Model', fontsize=14)
plt.grid(True)
plt.savefig('temperature_evolution_5cm_enhanced.png', dpi=600, bbox_inches='tight')
plt.show()

# Analyze impact of skin on ultrasound transmission
skin_impact = {
    'initial_intensity': I0,
    'intensity_after_epidermis': I[np.abs(z - 0.1).argmin()],
    'intensity_after_dermis': I[np.abs(z - 0.4).argmin()],
    'intensity_after_hypodermis': I[np.abs(z - 1.0).argmin()],
    'intensity_at_pancreas': I[np.abs(z - 5.0).argmin()],
    'attenuation_by_skin_pct': (1 - I[np.abs(z - 1.0).argmin()]/I0) * 100
}

# Save analysis to CSV
pd.DataFrame({
    'Metric': list(skin_impact.keys()),
    'Value': list(skin_impact.values())
}).to_csv('skin_impact_analysis.csv', index=False)

print("\nSkin Impact Analysis:")
print(f"Initial intensity: {skin_impact['initial_intensity']:.2f} W/cm²")
print(f"After passing through skin: {skin_impact['intensity_after_hypodermis']:.2f} W/cm²")
print(f"Attenuation by skin: {skin_impact['attenuation_by_skin_pct']:.1f}%")
print(f"Maximum temperature reached at target depth: {T_history[target_depth_idx,-1]:.1f}°C")

# Original function (might cause errors)
def compare_with_hitu_simulator(sim_temp, z):
    """Compare with HITU Simulator data from Zderic paper"""

    # Data extracted from HITU Simulator images (from Zderic's paper)
    hitu_z = np.array([0, 1, 2, 3, 4, 5, 6, 7])
    hitu_temp = np.array([37.0, 37.1, 37.25, 37.55, 37.35, 37.3, 37.25, 37.2])

    # Interpolate simulated data to match HITU data points
    from scipy.interpolate import interp1d
    sim_interp = interp1d(z, sim_temp, bounds_error=False, fill_value="extrapolate")
    sim_temp_interp = sim_interp(hitu_z)

    # Calculate comparison metrics
    abs_diff = np.abs(sim_temp_interp - hitu_temp)
    rel_diff = 100 * abs_diff / hitu_temp

    metrics = {
        'mean_abs_diff': np.mean(abs_diff),
        'max_abs_diff': np.max(abs_diff),
        'mean_rel_diff': np.mean(rel_diff),
        'rmse': np.sqrt(np.mean((sim_temp_interp - hitu_temp)**2))
    }

    # Plot comparison
    plt.figure(figsize=(10, 6))
    plt.plot(z, sim_temp, 'r-', label='Enhanced Model', linewidth=2)
    plt.plot(hitu_z, hitu_temp, 'b--', label='HITU Simulator', linewidth=2)

    # Highlight pancreas region
    plt.axvspan(4, 6.5, color='yellow', alpha=0.2, label='Pancreas Region')

    plt.xlabel('Depth (cm)', fontsize=12)
    plt.ylabel('Temperature (°C)', fontsize=12)
    plt.title(f"Model vs HITU Simulator\nRMSE: {metrics['rmse']:.2f}°C", fontsize=14)
    plt.grid(True)
    plt.legend(fontsize=12)
    plt.savefig('hitu_simulator_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Save comparison metrics
    metrics_df = pd.DataFrame({
        'Metric': list(metrics.keys()),
        'Value': [f"{v:.4f}" for v in metrics.values()]
    })
    metrics_df.to_csv('hitu_comparison_metrics.csv', index=False)

    # Print comparison summary
    print(f"\nComparison with HITU Simulator:")
    print(f"RMSE: {metrics['rmse']:.4f}°C")
    print(f"Mean Absolute Difference: {metrics['mean_abs_diff']:.4f}°C")
    print(f"Maximum Absolute Difference: {metrics['max_abs_diff']:.4f}°C")
    print(f"Mean Percentage Difference: {metrics['mean_rel_diff']:.2f}%")

    return metrics

# Direct comparison bypass function - this will be used if the main function fails
def direct_hitu_comparison(sim_temp, z):
    """Direct comparison with HITU data without using the comparison function"""
    # HITU Simulator data from the figures
    hitu_z = np.array([0, 1, 2, 3, 4, 5, 6, 7])
    hitu_temp = np.array([37.0, 37.1, 37.25, 37.55, 37.35, 37.3, 37.25, 37.2])

    # Get simulated temperatures at exactly the HITU z positions
    from scipy.interpolate import interp1d
    sim_interp = interp1d(z, sim_temp, bounds_error=False, fill_value="extrapolate")
    sim_at_hitu_points = sim_interp(hitu_z)

    # Calculate key metrics
    abs_diff = np.abs(sim_at_hitu_points - hitu_temp)
    rmse = np.sqrt(np.mean((sim_at_hitu_points - hitu_temp)**2))
    max_diff = np.max(abs_diff)

    # Create comparison table
    comparison_df = pd.DataFrame({
        'Depth (cm)': hitu_z,
        'HITU Temp (°C)': hitu_temp,
        'Model Temp (°C)': sim_at_hitu_points,
        'Absolute Diff (°C)': abs_diff
    })

    # Save to CSV
    comparison_df.to_csv('hitu_direct_comparison.csv', index=False)

    # Plot comparison
    plt.figure(figsize=(10, 6))
    plt.plot(z, sim_temp, 'r-', label='Enhanced Model', linewidth=2)
    plt.plot(hitu_z, hitu_temp, 'bo--', label='HITU Simulator', linewidth=2, markersize=6)
    plt.axvspan(4, 6.5, color='yellow', alpha=0.2, label='Pancreas Region')
    plt.xlabel('Depth (cm)', fontsize=12)
    plt.ylabel('Temperature (°C)', fontsize=12)
    plt.title(f"Direct Comparison with HITU Simulator\nRMSE: {rmse:.4f}°C", fontsize=14)
    plt.grid(True)
    plt.legend(fontsize=12)
    plt.savefig('hitu_direct_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Print results
    print(f"\nDirect Comparison with HITU Simulator:")
    print(f"RMSE: {rmse:.4f}°C")
    print(f"Maximum difference: {max_diff:.4f}°C")

    return comparison_df

# Analyze pancreas heating specifically
def analyze_pancreas_heating():
    """Analyze heating effects in the pancreas region"""
    # Find pancreas indices
    pancreas_indices = np.where((z >= 4.0) & (z <= 6.5))

    # Extract pancreas temperatures
    pancreas_temps = T[pancreas_indices]

    # Calculate statistics
    min_temp = np.min(pancreas_temps)
    max_temp = np.max(pancreas_temps)
    mean_temp = np.mean(pancreas_temps)
    std_temp = np.std(pancreas_temps)

    # Generate summary table
    print("\nPancreas Thermal Analysis:")
    print(f"Minimum temperature: {min_temp:.2f}°C")
    print(f"Maximum temperature: {max_temp:.2f}°C")
    print(f"Mean temperature: {mean_temp:.2f}°C")
    print(f"Standard deviation: {std_temp:.2f}°C")

    # Display position of maximum heating
    max_idx = np.argmax(pancreas_temps)
    max_position = z[pancreas_indices][max_idx]
    print(f"Position of maximum temperature: {max_position:.2f} cm (depth from surface)")

    # Save results
    results_df = pd.DataFrame({
        'Metric': ['Minimum', 'Maximum', 'Mean', 'Std Dev', 'Max Position'],
        'Value': [f"{min_temp:.2f}°C", f"{max_temp:.2f}°C", f"{mean_temp:.2f}°C",
                 f"{std_temp:.2f}°C", f"{max_position:.2f} cm"]
    })
    results_df.to_csv('pancreas_thermal_analysis.csv', index=False)

    return {
        'min_temp': min_temp,
        'max_temp': max_temp,
        'mean_temp': mean_temp,
        'std_temp': std_temp,
        'max_position': max_position
    }

# Run analyses
pancreas_metrics = analyze_pancreas_heating()

# BYPASS IMPLEMENTATION - Skip the problematic function entirely
# Instead of trying the compare_with_hitu_simulator function which causes errors,
# directly use the bypass function
print("\nUsing direct comparison bypass to avoid interpolation errors...")
direct_comparison = direct_hitu_comparison(T, z)

# Save all simulation data for further analysis
sim_data = pd.DataFrame({
    'Depth_cm': z,
    'Final_Temperature_C': T,
    'Initial_Temperature_C': T_history[:,0],
    'Acoustic_Intensity_W_per_cm2': I,
    'Attenuation_dB_per_cm': att_dB
})
sim_data.to_csv('enhanced_simulation_results.csv', index=False)

print("\nSimulation and analysis complete. All results saved to CSV files and plots.")
# Add the following code at the end of your existing script to simulate a focused transducer

print("\n\n=============================================")
print("FOCUSED TRANSDUCER SIMULATION (1.5 cm radius, focal depth 3.96 cm)")
print("=============================================\n")

def simulate_focused_transducer():
    # Focused transducer parameters
    transducer_radius = 1.5  # cm
    focal_depth = 3.96  # cm
    f_number = focal_depth / (2 * transducer_radius)

    # Reuse the same tissue properties and grid as the unfocused simulation
    global z, tissue_layers, att_dB, k_thermal, c_p, density, blood_perfusion

    # Calculate beam intensity profile for focused transducer
    # Using analytical model for spherically focused transducer
    I_focused = np.zeros_like(z)

    # Calculate on-axis intensity distribution for a focused transducer
    # Based on O'Neil's model for spherically focused transducers
    wavelength_cm = (sound_speed_default / frequency) * 100  # wavelength in cm
    k = 2 * np.pi / wavelength_cm  # wave number in cm^-1

    for i, zi in enumerate(z):
        # Distance from transducer, normalized to focal length
        normalized_z = zi / focal_depth

        if zi == 0:  # At transducer surface
            I_focused[i] = I0
        else:
            # Avoid division by zero and other numerical issues
            if abs(normalized_z - 1.0) < 1e-10:  # At focal point
                I_focused[i] = I0 * (k * transducer_radius**2 / focal_depth)**2
            else:
                # Apply O'Neil's formula for on-axis intensity
                I_focused[i] = I0 * (np.sin(k * transducer_radius**2 * (1/zi - 1/focal_depth) / 2))**2

    # Apply tissue attenuation to the focused beam
    for i in range(1, len(z)):
        delta_att = att_dB[i-1] * dz
        I_focused[i] *= 10**(-delta_att/10)

    # Normalize to ensure peak intensity matches the desired I0
    peak_idx = np.abs(z - focal_depth).argmin()
    normalization_factor = I0 * 4 / I_focused[peak_idx]  # Focused gain of approximately 4x at focus
    I_focused = I_focused * normalization_factor

    # Plot focused beam intensity profile
    plt.figure(figsize=(10, 6))
    plt.plot(z, I_focused, 'r-', linewidth=2, label='Focused Beam Intensity')
    plt.plot(z, I, 'b--', linewidth=1.5, label='Unfocused Beam (for comparison)')
    plt.axvline(x=focal_depth, color='green', linestyle=':', label=f'Focal Point: {focal_depth} cm')

    # Add tissue layer markers
    for layer in tissue_layers:
        plt.axvline(x=layer['start'], color='gray', linestyle=':', alpha=0.7)
        plt.text(layer['start'] + (layer['end']-layer['start'])/2, I0*5.5,
                 layer['name'], rotation=90, va='top', ha='center', fontsize=9)

    plt.xlabel('Depth (cm)', fontsize=12)
    plt.ylabel('Intensity (W/cm²)', fontsize=12)
    plt.title('Focused vs Unfocused Beam Intensity Profile', fontsize=14)
    plt.grid(True)
    plt.legend(fontsize=12)
    plt.savefig('focused_beam_intensity.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Thermal simulation for focused transducer
    print("Running thermal simulation for focused transducer...")

    # Convert attenuation to Np/m for heating term
    alpha_Np = att_dB * (np.log(10)/20) * 100  # Convert dB/cm to Np/m

    # Calculate heating term Q (W/m³) at each depth for focused beam
    Q_focused = 2 * alpha_Np * I_focused * 10000  # Convert I from W/cm² to W/m²

    # Thermal simulation with the focused beam
    T_focused = np.ones_like(z)*37  # Initial temperature
    T_focused_history = np.zeros((len(z), nt))
    T_focused_history[:,0] = T_focused

    # Time evolution for focused beam
    for n in tqdm(range(1, nt)):
        dT = np.zeros_like(T_focused)
        for i in range(1, len(z)-1):
            # Diffusion term
            diffusion = kappa[i] * (T_focused[i+1] - 2*T_focused[i] + T_focused[i-1]) / dz_m**2

            # Perfusion term
            perfusion = blood_perfusion[i] * blood_density * blood_specific_heat * (blood_temp - T_focused[i]) / density[i] / c_p[i]

            # Source term
            source = Q_focused[i] / (density[i] * c_p[i])

            # Combined temperature change
            dT[i] = dt * (diffusion + perfusion + source)

        # Boundary conditions (adiabatic)
        dT[0] = dT[1]
        dT[-1] = dT[-2]

        T_focused = T_focused + dT
        T_focused_history[:,n] = T_focused

    # Plot temperature distribution for focused beam
    plt.figure(figsize=(10, 6))
    plt.plot(z, T_focused, 'r-', linewidth=2, label='Focused Beam Temperature')
    plt.plot(z, T, 'b--', linewidth=1.5, label='Unfocused Beam Temperature')
    plt.axvline(x=focal_depth, color='green', linestyle=':', label=f'Focal Point: {focal_depth} cm')

    # Add tissue layer markers
    for layer in tissue_layers:
        plt.axvline(x=layer['start'], color='gray', linestyle=':', alpha=0.7)
        mid_point = layer['start'] + (layer['end']-layer['start'])/2
        plt.text(mid_point, plt.ylim()[1] - 0.2, layer['name'],
                 rotation=90, va='top', ha='center', fontsize=9)

    plt.xlabel('Depth (cm)', fontsize=12)
    plt.ylabel('Temperature (°C)', fontsize=12)
    plt.title(f'Temperature Distribution After {sonication_time}s Sonication: Focused vs Unfocused', fontsize=14)
    plt.grid(True)
    plt.legend(fontsize=12)
    plt.savefig('focused_temperature_distribution.png', dpi=900, bbox_inches='tight')
    plt.show()

    # Analyze pancreas heating for focused beam
    pancreas_indices = np.where((z >= 4.0) & (z <= 6.5))
    pancreas_temps = T_focused[pancreas_indices]

    min_temp = np.min(pancreas_temps)
    max_temp = np.max(pancreas_temps)
    mean_temp = np.mean(pancreas_temps)
    std_temp = np.std(pancreas_temps)

    print("\nPancreas Thermal Analysis (Focused Beam):")
    print(f"Minimum temperature: {min_temp:.2f}°C")
    print(f"Maximum temperature: {max_temp:.2f}°C")
    print(f"Mean temperature: {mean_temp:.2f}°C")
    print(f"Standard deviation: {std_temp:.2f}°C")

    max_idx = np.argmax(pancreas_temps)
    max_position = z[pancreas_indices][max_idx]
    print(f"Position of maximum temperature: {max_position:.2f} cm (depth from surface)")

    # Save results for focused beam
    focused_results_df = pd.DataFrame({
        'Metric': ['Minimum', 'Maximum', 'Mean', 'Std Dev', 'Max Position'],
        'Value': [f"{min_temp:.2f}°C", f"{max_temp:.2f}°C", f"{mean_temp:.2f}°C",
                 f"{std_temp:.2f}°C", f"{max_position:.2f} cm"]
    })
    focused_results_df.to_csv('focused_pancreas_thermal_analysis.csv', index=False)

    # Compare with HITU simulator data
    direct_comparison_focused = direct_hitu_comparison(T_focused, z)

    # Save comparison between focused and unfocused
    comparison_df = pd.DataFrame({
        'Depth (cm)': z,
        'Unfocused I (W/cm²)': I,
        'Focused I (W/cm²)': I_focused,
        'Unfocused T (°C)': T,
        'Focused T (°C)': T_focused,
        'Difference (°C)': T_focused - T
    })
    comparison_df.to_csv('focused_vs_unfocused_comparison.csv', index=False)

    return {
        'I_focused': I_focused,
        'T_focused': T_focused,
        'pancreas_metrics': {
            'min_temp': min_temp,
            'max_temp': max_temp,
            'mean_temp': mean_temp,
            'std_temp': std_temp,
            'max_position': max_position
        }
    }

# Run the focused transducer simulation
focused_results = simulate_focused_transducer()

print("\nSimulation complete. Comparison between focused and unfocused transducers saved to CSV.")
# Add this code at the end of your script to compare with Zderic's model

def run_pulsed_simulation(duty_factor, duration_min):
    """Run a simulation with pulsed ultrasound to match Zderic's experiments"""
    print(f"\nRunning simulation with {duty_factor*100}% duty factor for {duration_min} minutes...")

    # Set up parameters
    duration_s = duration_min * 60
    nt_duty = int(duration_s / dt)

    # Initial conditions
    T_duty = np.ones_like(z) * 37.0
    T_history_duty = np.zeros((len(z), min(30000, nt_duty)))  # Limit history size to avoid memory issues
    T_history_duty[:,0] = T_duty

    # Apply duty factor by scaling the heating term
    Q_duty = Q * duty_factor

    # Simplified simulation (scaling heating rather than full pulsing)
    for n in tqdm(range(1, nt_duty)):
        dT = np.zeros_like(T_duty)
        for i in range(1, len(z)-1):
            # Diffusion term
            diffusion = kappa[i] * (T_duty[i+1] - 2*T_duty[i] + T_duty[i-1]) / dz_m**2

            # Perfusion term
            perfusion = blood_perfusion[i] * blood_density * blood_specific_heat * (blood_temp - T_duty[i]) / density[i] / c_p[i]

            # Source term (scaled by duty factor)
            source = Q_duty[i] / (density[i] * c_p[i])

            # Combined temperature change
            dT[i] = dt * (diffusion + perfusion + source)

        # Boundary conditions
        dT[0] = dT[1]
        dT[-1] = dT[-2]

        T_duty = T_duty + dT
        if n < 30000:  # Store in history if within limits
            T_history_duty[:,n] = T_duty

    # Calculate max temperatures
    pancreas_indices = np.where((z >= 4.0) & (z <= 6.5))
    duty_pancreas_max = np.max(T_duty[pancreas_indices])
    duty_overall_max = np.max(T_duty)

    # Plot temperature distribution
    plt.figure(figsize=(10, 6))
    plt.plot(z, T_duty, 'r-', linewidth=2, label=f'{duty_factor*100}% Duty')
    plt.plot(z, T, 'b--', linewidth=1.5, label='Original Simulation')

    # Add vertical lines for tissue layers
    for layer in tissue_layers:
        plt.axvline(x=layer['start'], color='gray', linestyle=':', alpha=0.5)

    plt.axvspan(4, 6.5, color='yellow', alpha=0.2, label='Pancreas Region')

    plt.xlabel('Depth (cm)', fontsize=12)
    plt.ylabel('Temperature (°C)', fontsize=12)
    plt.title(f'Temperature Distribution: {duty_factor*100}% Duty Factor, {duration_min} min', fontsize=14)
    plt.grid(True)
    plt.legend(fontsize=12)
    plt.savefig(f'temp_distribution_{int(duty_factor*100)}pct_duty.png', dpi=300, bbox_inches='tight')
    plt.show()

    return duty_pancreas_max, duty_overall_max, T_duty

def compare_with_zderic_model():
    """Compare your current simulation results with Zderic's paper"""
    print("\n=== COMPARING WITH VESNA ZDERIC'S MODEL ===\n")

    # Convert current simulation duration to minutes
    current_duration_min = sonication_time / 60

    # Zderic's data from Figure 4 in the paper (estimated values)
    zderic_data = {
        'duration_min': [1, 2, 3, 4, 5],  # minutes
        'pancreas_temp_10pct': [37.1, 37.2, 37.3, 37.4, 37.5],  # 10% duty factor
        'pancreas_temp_25pct': [37.3, 37.5, 37.7, 37.8, 38],  # 25% duty factor
        'pancreas_temp_50pct': [37.5, 38, 38.3, 38.5, 38.8],  # 50% duty factor
        'pancreas_temp_100pct': [38.3, 39.0, 39.5, 40.1, 40.5],  # 100% duty factor
        'overall_temp_10pct': [40, 43, 45, 47, 49],    # 10% duty factor
        'overall_temp_25pct': [43, 49, 52, 55.0, 59.0],    # 25% duty factor
        'overall_temp_50pct': [50, 60, 68, 75.0, 82.0],    # 50% duty factor
        'overall_temp_100pct': [65.0, 80.0, 100.0, 115.0, 125.0]    # 100% duty factor
    }

    # Get your simulation's max temperatures
    pancreas_indices = np.where((z >= 4.0) & (z <= 6.5))
    your_max_pancreas_temp = np.max(T[pancreas_indices])
    your_max_overall_temp = np.max(T)

    print(f"Your simulation parameters:")
    print(f"  Duration: {current_duration_min:.2f} minutes")
    print(f"  Intensity: {I0} W/cm²")
    print(f"  Max pancreas temperature: {your_max_pancreas_temp:.2f}°C")
    print(f"  Max overall temperature: {your_max_overall_temp:.2f}°C")

    # Create Zderic-style visualization
    plt.figure(figsize=(12, 10))

    # Pancreas temperature plot
    plt.subplot(2, 1, 1)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_10pct'], 'b-', label='OnShape 10% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_25pct'], 'g-', label='OnShape 25% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_50pct'], 'y-', label='OnShape 50% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_100pct'], 'r-', label='OnShape 100% Duty', linewidth=2)

    # Add your simulation point
    plt.plot(current_duration_min, your_max_pancreas_temp, 'ko', markersize=10, label='Your Simulation')

    plt.xlabel('Sonication Duration (min)', fontsize=12)
    plt.ylabel('Maximum Pancreas Temperature (°C)', fontsize=12)
    plt.title('Pancreas Temperature: Your Simulation vs. Zderic Model', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend()

    # Overall temperature plot
    plt.subplot(2, 1, 2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_10pct'], 'b-', label='OnShape 10% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_25pct'], 'g-', label='OnShape 25% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_50pct'], 'y-', label='OnShape 50% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_100pct'], 'r-', label='OnShape 100% Duty', linewidth=2)

    # Add your simulation point
    plt.plot(current_duration_min, your_max_overall_temp, 'ko', markersize=10, label='Your Simulation')

    plt.xlabel('Sonication Duration (min)', fontsize=12)
    plt.ylabel('Maximum Overall Temperature (°C)', fontsize=12)
    plt.title('Overall Temperature: Your Simulation vs. Zderic Model', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend()

    plt.tight_layout()
    plt.savefig('zderic_model_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    return your_max_pancreas_temp, your_max_overall_temp

def run_multi_duty_simulation():
    """Run simulations with multiple duty factors like in Zderic's paper"""
    print("\n=== RUNNING MULTI-DUTY FACTOR SIMULATIONS ===\n")

    # Use same duty factors and durations as Zderic's paper
    duty_factors = [0.1, 0.25, 0.5, 1.0]  # 10%, 25%, 50%, 100%
    durations = [1, 2, 3, 4, 5]  # minutes

    # Initialize results storage
    results = {
        'Duration': [],
        'Duty_Factor': [],
        'Pancreas_Max_Temp': [],
        'Overall_Max_Temp': []
    }

    # Run simulations for key combinations
    for duty in duty_factors:
        for duration in durations:
            if (duty == 1.0 and duration > 3) or (duty == 0.5 and duration > 4):
                # Skip longer durations for high duty factors (would overheat)
                print(f"Skipping {duty*100}% duty, {duration} min (would overheat)")
                results['Duration'].append(duration)
                results['Duty_Factor'].append(duty*100)
                results['Pancreas_Max_Temp'].append(None)
                results['Overall_Max_Temp'].append(None)
                continue

            print(f"Simulating {duty*100}% duty, {duration} min")
            pancreas_max, overall_max, _ = run_pulsed_simulation(duty, duration)

            results['Duration'].append(duration)
            results['Duty_Factor'].append(duty*100)
            results['Pancreas_Max_Temp'].append(pancreas_max)
            results['Overall_Max_Temp'].append(overall_max)

    # Save results to CSV
    results_df = pd.DataFrame(results)
    results_df.to_csv('zderic_duty_comparison.csv', index=False)

    # Create visualization like Figure 4 in Zderic's paper
    plt.figure(figsize=(14, 10))

    # Plot pancreas temperatures
    plt.subplot(2, 1, 1)
    for duty in duty_factors:
        df_subset = results_df[results_df['Duty_Factor'] == duty*100]
        plt.plot(df_subset['Duration'], df_subset['Pancreas_Max_Temp'], 'o-',
                 linewidth=2, label=f'{int(duty*100)}% Duty Factor')

    plt.xlabel('Duration (minutes)', fontsize=12)
    plt.ylabel('Maximum Pancreas Temperature (°C)', fontsize=12)
    plt.title('Effect of Duty Factor and Duration on Pancreas Temperature', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend()

    # Plot overall temperatures
    plt.subplot(2, 1, 2)
    for duty in duty_factors:
        df_subset = results_df[results_df['Duty_Factor'] == duty*100]
        plt.plot(df_subset['Duration'], df_subset['Overall_Max_Temp'], 'o-',
                 linewidth=2, label=f'{int(duty*100)}% Duty Factor')

    plt.xlabel('Duration (minutes)', fontsize=12)
    plt.ylabel('Maximum Overall Temperature (°C)', fontsize=12)
    plt.title('Effect of Duty Factor and Duration on Overall Temperature', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend()

    plt.tight_layout()
    plt.savefig('zderic_duty_duration_effects.png', dpi=300, bbox_inches='tight')
    plt.show()

    return results_df

# Compare current simulation with Zderic's model
pancreas_max, overall_max = compare_with_zderic_model()

# To run pulsed simulations with different duty factors, uncomment:
# Example: 10% duty factor for 5 minutes
# pancreas_max_10pct, overall_max_10pct, temps_10pct = run_pulsed_simulation(duty_factor=0.1, duration_min=5)

# For a full comparison with Zderic's paper results, uncomment:
# multi_duty_results = run_multi_duty_simulation()

def compare_with_zderic_model_full():
    """Compare your full simulation results with Zderic's paper at multiple time points"""
    print("\n=== COMPARING FULL TEMPERATURE PROGRESSION WITH ZDERIC'S MODEL ===\n")

    # Define time points to extract (in minutes)
    minute_points = np.array([1, 2, 3, 4, 5]) * 60  # Convert to seconds

    # Find nearest indices in time_points array
    time_indices = []
    for sec in minute_points:
        if sec <= sonication_time:
            idx = np.abs(time_points - sec).argmin()
            time_indices.append(idx)
        else:
            print(f"Warning: {sec/60} minute point exceeds simulation time")

    # Extract pancreas and overall max temperatures at each time point
    pancreas_indices = np.where((z >= 4.0) & (z <= 6.5))
    your_pancreas_temps = []
    your_overall_temps = []
    actual_minutes = []

    for idx in time_indices:
        temp_at_time = T_history[:, idx]
        pancreas_temp = np.max(temp_at_time[pancreas_indices])
        overall_temp = np.max(temp_at_time)
        your_pancreas_temps.append(pancreas_temp)
        your_overall_temps.append(overall_temp)
        actual_minutes.append(time_points[idx] / 60)  # Convert back to minutes

    # Zderic's data from Figure 4 in the paper (estimated values)
    zderic_data = {
        'duration_min': [1, 2, 3, 4, 5],  # minutes
        'pancreas_temp_10pct': [37.1, 37.2, 37.3, 37.4, 37.5],  # 10% duty factor
        'pancreas_temp_25pct': [37.3, 37.5, 37.7, 37.8, 38],  # 25% duty factor
        'pancreas_temp_50pct': [37.5, 38, 38.3, 38.5, 38.8],  # 50% duty factor
        'pancreas_temp_100pct': [38.3, 39.0, 39.5, 40.1, 40.5],  # 100% duty factor
        'overall_temp_10pct': [40, 43, 45, 47, 49],    # 10% duty factor
        'overall_temp_25pct': [43, 49, 52, 55.0, 59.0],    # 25% duty factor
        'overall_temp_50pct': [50, 60, 68, 75.0, 82.0],    # 50% duty factor
        'overall_temp_100pct': [65.0, 80.0, 100.0, 115.0, 125.0],    # 100% duty factor
        'obese_pancreas_temp_10pct': [37.2, 37.4, 37.7, 38, 38.2],  # 10% duty factor
        'obese_pancreas_temp_25pct': [38, 38.4, 38.9, 39.2, 39.7],  # 25% duty factor
        'obese_pancreas_temp_50pct': [38.7, 39.8, 40.8, 41.5, 42.2],  # 50% duty factor
        'obese_pancreas_temp_100pct': [40.5, 42.8, 44.8, 46, 47.2],  # 100% duty factor
        'obese_overall_temp_10pct': [42, 46, 49, 51, 52],    # 10% duty factor
        'obese_overall_temp_25pct': [51, 56, 65, 75.0, 80.0],    # 25% duty factor
        'obese_overall_temp_50pct': [70, 75, 98, 110, 125.0],    # 50% duty factor
        'obese_overall_temp_100pct': [105, 125.0, 155.0, 180.0, 215.0]    # 100% duty factor
    }

    # Print the extracted values
    print("Your simulation temperature progression:")
    print("Duration (min) | Pancreas Max (°C) | Overall Max (°C)")
    for i, minute in enumerate(actual_minutes):
        print(f"{minute:12.2f} | {your_pancreas_temps[i]:16.2f} | {your_overall_temps[i]:15.2f}")

    # Create Zderic-style visualization
    plt.figure(figsize=(12, 10))

    # Pancreas temperature plot
    plt.subplot(2, 1, 1)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_10pct'], 'b-', label='OnShape 10% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_25pct'], 'g-', label='OnShape 25% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_50pct'], 'y-', label='OnShape 50% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['pancreas_temp_100pct'], 'r-', label='OnShape 100% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_pancreas_temp_10pct'], 'b-', label='OnShape 10% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_pancreas_temp_25pct'], 'g-', label='OnShape 25% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_pancreas_temp_50pct'], 'y-', label='OnShape 50% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_pancreas_temp_100pct'], 'r-', label='OnShape 100% Duty', linewidth=2)

    # Add your simulation curve
    plt.plot(actual_minutes, your_pancreas_temps, 'ko-', markersize=8, linewidth=2, label='Your Simulation')

    plt.xlabel('Sonication Duration (min)', fontsize=12)
    plt.ylabel('Maximum Pancreas Temperature (°C)', fontsize=12)
    plt.title('Pancreas Temperature: Your Simulation vs. OnShape Model', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend()

    # Overall temperature plot
    plt.subplot(2, 1, 2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_10pct'], 'b-', label='OnShape 10% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_25pct'], 'g-', label='OnShape 25% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_50pct'], 'y-', label='OnShape 50% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['overall_temp_100pct'], 'r-', label='OnShape 100% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_overall_temp_10pct'], 'b-', label='OnShape 10% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_overall_temp_25pct'], 'g-', label='OnShape 25% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_overall_temp_50pct'], 'y-', label='OnShape 50% Duty', linewidth=2)
    plt.plot(zderic_data['duration_min'], zderic_data['obese_overall_temp_100pct'], 'r-', label='OnShape 100% Duty', linewidth=2)

    # Add your simulation curve
    plt.plot(actual_minutes, your_overall_temps, 'ko-', markersize=8, linewidth=2, label='Your Simulation')

    plt.xlabel('Sonication Duration (min)', fontsize=12)
    plt.ylabel('Maximum Overall Temperature (°C)', fontsize=12)
    plt.title('Overall Temperature: Your Simulation vs. OnShape Model', fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend()

    plt.tight_layout()
    plt.savefig('zderic_full_comparison.png', dpi=900, bbox_inches='tight')
    plt.show()

    # Save the data to CSV
    comparison_df = pd.DataFrame({
        'Duration_min': actual_minutes,
        'Your_Pancreas_Temp': your_pancreas_temps,
        'Your_Overall_Temp': your_overall_temps,
    })

    # Add Zderic's data columns if they match the number of points we have
    if len(actual_minutes) <= len(zderic_data['duration_min']):
        comparison_df['Zderic_Pancreas_10pct'] = zderic_data['pancreas_temp_10pct'][:len(actual_minutes)]
        comparison_df['Zderic_Pancreas_25pct'] = zderic_data['pancreas_temp_25pct'][:len(actual_minutes)]
        comparison_df['Zderic_Pancreas_50pct'] = zderic_data['pancreas_temp_50pct'][:len(actual_minutes)]
        comparison_df['Zderic_Pancreas_100pct'] = zderic_data['pancreas_temp_100pct'][:len(actual_minutes)]
        comparison_df['Zderic_Overall_10pct'] = zderic_data['overall_temp_10pct'][:len(actual_minutes)]
        comparison_df['Zderic_Overall_25pct'] = zderic_data['overall_temp_25pct'][:len(actual_minutes)]
        comparison_df['Zderic_Overall_50pct'] = zderic_data['overall_temp_50pct'][:len(actual_minutes)]
        comparison_df['Zderic_Overall_100pct'] = zderic_data['overall_temp_100pct'][:len(actual_minutes)]

    comparison_df.to_csv('zderic_full_comparison.csv', index=False)

    return your_pancreas_temps, your_overall_temps

# Add this line after running your simulation to see the full comparison:
compare_with_zderic_model_full()

def run_pulsed_simulation(duty_factor, duration_min):
    """Run a simulation with pulsed ultrasound"""
    print(f"\nRunning {duty_factor*100}% duty factor simulation for {duration_min} minutes...")

    duration_sec = duration_min * 60  # Now single value
    nt = int(duration_sec / dt)

    # Initialize temperature array
    T_pulsed = np.ones_like(z) * 37.0
    T_history_pulsed = np.zeros((len(z), nt))
    T_history_pulsed[:,0] = T_pulsed

    # Calculate pulse timing
    pulse_period = 1.0  # 1 second period for duty cycle
    on_time = pulse_period * duty_factor

    for n in tqdm(range(1, nt)):
        current_time = n * dt
        # Determine if in ON/OFF phase of duty cycle
        if (current_time % pulse_period) < on_time:
            Q_scaled = Q
        else:
            Q_scaled = 0 * Q

        dT = np.zeros_like(T_pulsed)
        for i in range(1, len(z)-1):
            diffusion = kappa[i] * (T_pulsed[i+1] - 2*T_pulsed[i] + T_pulsed[i-1]) / dz_m**2
            perfusion = blood_perfusion[i] * blood_density * blood_specific_heat * (blood_temp - T_pulsed[i]) / (density[i] * c_p[i])
            source = Q_scaled[i] / (density[i] * c_p[i])
            dT[i] = dt * (diffusion + perfusion + source)

        # Boundary conditions
        dT[0] = dT[1]
        dT[-1] = dT[-2]

        T_pulsed += dT
        T_history_pulsed[:,n] = T_pulsed

    # Get maximum temperatures at each minute
    pancreas_indices = np.where((z >= 4.0) & (z <= 6.5))
    time_points = []
    pancreas_temps = []
    overall_temps = []

    # Sample at 1 minute intervals
    for minute in range(1, duration_min + 1):
        idx = int(minute * 60 / dt)
        if idx < nt:
            time_points.append(minute)
            pancreas_temps.append(np.max(T_history_pulsed[pancreas_indices, idx]))
            overall_temps.append(np.max(T_history_pulsed[:, idx]))

    return time_points, pancreas_temps, overall_temps

def run_all_duty_simulations():
    """Run simulations for all duty factors and durations"""
    duties = [0.10, 0.25, 0.50, 0.75, 1.00]
    durations = [1, 2, 3, 4, 5]  # minutes
    results = {}

    for duty in duties:
        for duration in durations:
            time_points, pancreas_temps, overall_temps = run_pulsed_simulation(duty, duration)
            key = f'{int(duty*100)}_{duration}min'
            results[key] = {
                'time_points': time_points,
                'pancreas_temps': pancreas_temps,
                'overall_temps': overall_temps
            }

    return results

def compare_with_zderic_model_full2():
    """Compare simulation results with Zderic's data"""
    print("\n=== COMPARING MULTIPLE DUTY FACTORS WITH ZDERIC'S MODEL ===\n")

    # Zderic's data
    zderic_data = {
        'duration_min': [1, 2, 3, 4, 5],
        'pancreas_temp_10pct': [37.1, 37.2, 37.3, 37.4, 37.5],
        'pancreas_temp_25pct': [37.3, 37.5, 37.7, 37.8, 38],
        'pancreas_temp_50pct': [37.5, 38, 38.3, 38.5, 38.8],
        'pancreas_temp_100pct': [38.3, 39.0, 39.5, 40.1, 40.5],
        'overall_temp_10pct': [40, 43, 45, 47, 49],
        'overall_temp_25pct': [43, 49, 52, 55.0, 59.0],
        'overall_temp_50pct': [50, 60, 68, 75.0, 82.0],
        'overall_temp_100pct': [65.0, 80.0, 100.0, 115.0, 125.0]
    }

    # Get simulation results
    your_results = run_all_duty_simulations()

    # Create comparison plots
    plt.figure(figsize=(14, 10))

    # Pancreas Temperature Comparison
    plt.subplot(2, 1, 1)
    colorz = {'10':'r', '25':'g', '50':'b', '75':'m', '100':'p'}

    # Plot Zderic's data
    for duty in ['10pct', '25pct', '50pct', '100pct']:
        plt.plot(zderic_data['duration_min'],
                zderic_data[f'pancreas_temp_{duty}'],
                colorz[duty[:2]]+'--',
                label=f'OnShape {duty}')

    # Plot simulation results
    for key in your_results:
        duty = key.split('_')[0]
        data = your_results[key]
        plt.plot(data['time_points'], data['pancreas_temps'],
                colorz[duty], markersize=5,
                label=f'Python {duty}%' if key.endswith('1min') else '')

    plt.ylabel('Pancreas Temperature (°C)')
    plt.title('Duty Factor Comparison: Pancreas Temperature')
    plt.legend()

    # Overall Temperature Comparison
    plt.subplot(2, 1, 2)
    for duty in ['10pct', '25pct', '50pct', '100pct']:
        plt.plot(zderic_data['duration_min'],
                zderic_data[f'overall_temp_{duty}'],
                colorz[duty[:2]]+'--',
                label=f'OnShape {duty}')

    for key in your_results:
        duty = key.split('_')[0]
        data = your_results[key]
        plt.plot(data['time_points'], data['overall_temps'],
                colorz[duty], markersize=5,
                label=f'Python {duty}%' if key.endswith('1min') else '')

    plt.xlabel('Sonication Duration (min)')
    plt.ylabel('Overall Temperature (°C)')
    plt.title('Duty Factor Comparison: Overall Temperature')
    plt.legend()
    plt.tight_layout()
    plt.savefig('duty_factor_comparison_onshape_python.png', dpi=900)
    plt.show()

compare_with_zderic_model_full2()

"""Part 2: Diabetic MD Simulation"""

# **Setup: Mount Google Drive and Install Required Libraries**
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Install necessary packages
!pip install MDAnalysis matplotlib

# Import necessary libraries
import numpy as np
import MDAnalysis as mda
from MDAnalysis.analysis.rms import rmsd
import matplotlib.pyplot as plt
import os

# Load structures
pdb_path_Kir6_2 = '/content/drive/MyDrive/Proteins/Kir6_2.pdb'
pdb_path_IRS1 = '/content/drive/MyDrive/Proteins/IRS1.pdb'

# Load into MDAnalysis Universe
Kir6_2 = mda.Universe(pdb_path_Kir6_2)
IRS1 = mda.Universe(pdb_path_IRS1)

# **Section 2: Simulate Diabetic Modifications (Glycation)**
# Apply modifications that simulate glycation on lysine (LYS) and arginine (ARG) residues

def apply_diabetic_modification(universe):
    # Copy structure to modify
    diabetic_universe = universe.copy()

    # Identify glycated amino acids (Lysine and Arginine)
    glycated_residues = diabetic_universe.select_atoms("resname LYS ARG")

    # Apply a small displacement to simulate glycation modification on these residues
    for atom in glycated_residues.atoms:
        atom.position += np.random.normal(0, 0.1, size=3)  # Small random displacement

    return diabetic_universe

# Create diabetic and non-diabetic versions
diabetic_Kir6_2 = apply_diabetic_modification(Kir6_2)
diabetic_IRS1 = apply_diabetic_modification(IRS1)

# **Section 3: Define Ultrasound Simulation Parameters**
frequency = 1e6   # 1 MHz
duty_cycle = 1.0  # 100%
duration = 300    # 5 minutes

# **Section 4: Function to Apply Ultrasound and Measure RMSD Changes**
def apply_ultrasound_effect(universe, frequency, duty_cycle, duration):
    rmsd_changes = []
    original_positions = universe.atoms.positions.copy()

    for t in range(int(duration)):
        # Apply pseudo-oscillatory "force" via atomic displacement (simplification)
        displacement = np.sin(2 * np.pi * frequency * t) * duty_cycle * 0.01
        universe.atoms.positions += displacement  # Oscillate positions
        rmsd_value = rmsd(universe.atoms.positions, original_positions)  # RMSD
        rmsd_changes.append(rmsd_value)
        universe.atoms.positions = original_positions  # Reset positions for next cycle

    return rmsd_changes

# **Section 5: Run Ultrasound Simulation**
# Run for each condition and protein type

print("Running simulation on Kir6_2 and IRS1 proteins...")

# Kir6_2
rmsd_Kir6_2_diabetic = apply_ultrasound_effect(diabetic_Kir6_2, frequency, duty_cycle, duration)
rmsd_Kir6_2_nondiabetic = apply_ultrasound_effect(Kir6_2, frequency, duty_cycle, duration)

# IRS1
rmsd_IRS1_diabetic = apply_ultrasound_effect(diabetic_IRS1, frequency, duty_cycle, duration)
rmsd_IRS1_nondiabetic = apply_ultrasound_effect(IRS1, frequency, duty_cycle, duration)

# **Section 6: Plot Results**
# Plot RMSD changes over time

plt.figure(figsize=(12, 6))
time = np.arange(duration)
# Define the path to save files in Google Drive
output_dir = "/content/drive/MyDrive/Proteins"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Kir6_2 Plot
plt.subplot(1, 2, 1)
plt.plot(time, rmsd_Kir6_2_diabetic, label='Diabetic Kir6.2', color='red')
plt.plot(time, rmsd_Kir6_2_nondiabetic, label='Non-Diabetic Kir6.2', color='blue')
plt.title('Kir6.2 RMSD Changes under Ultrasound')
plt.xlabel('Time (s)')
plt.ylabel('RMSD (nm)')
plt.legend()
plt.savefig(os.path.join(output_dir, 'Kir6_2_RMSD_Changes.png'))  # Save plot to Google Drive
# IRS1 Plot
plt.subplot(1, 2, 2)
plt.plot(time, rmsd_IRS1_diabetic, label='Diabetic IRS1', color='red')
plt.plot(time, rmsd_IRS1_nondiabetic, label='Non-Diabetic IRS1', color='blue')
plt.title('IRS1 RMSD Changes under Ultrasound')
plt.xlabel('Time (s)')
plt.ylabel('RMSD (nm)')
plt.legend()
plt.savefig(os.path.join(output_dir, 'IRS1_RMSD_Changes.png'))  # Save plot to Google Drive
plt.tight_layout()
plt.show()